### ISSUE TITLE
Patient find not working

### ISSUE THREAD

**Issue by daitenshionyan** [AY2223S2-CS2103-F11-3/tp#125]

**Comment by daitenshionyan** [comment]
Apparently it is working just that it requires very specific `Strings`. Like you will have to type `alex` to find `Alex Yeoh` in sample data instead of just `a`.

I think we should create a more flexible find.

**Comment by francisyzy** [comment]
it matches by word, like typing `ale` also won't match Alex. Will look into it

**Comment by daitenshionyan** [comment]
Shall we make this a 1.3 problem??

**Comment by francisyzy** [comment]
Let me try and see if I can fix it now. I think I found the lines that might be the problem

https://github.com/AY2223S2-CS2103-F11-3/tp/blob/b172b138e5582d7e855f45ec1f79bda7d90e77d2/src/main/java/seedu/vms/model/FilteredIdDataMap.java#L50-L65

**Comment by francisyzy** [comment]
It was changed 6 years ago from contains ignore case to this contains word thingy... not sure if its a bug then

https://github.com/francisyzy/tp/commit/38a5a4dd871a6f58c673131992d68b9675ff6fba

**Comment by daitenshionyan** [comment]
I think it is a bug.

This does not find Bernice Yu
```text
patient find bernic
```

**Comment by francisyzy** [comment]
yea, was testing it now and the old search function doesn't work, tried to search `a` also cannot find.

**Comment by daitenshionyan** [comment]
I think this can be fixed by making the test method as such:

```java
    @Override
    public boolean test(Patient patient) {
        String name = patient.getName().fullName.toUpperCase();
        for (String keyword : keywords) {
            if (!name.contains(keyword.toUpperCase())) {
                return false;
            }
        }
        return true;
    }
```

**Comment by daitenshionyan** [comment]
I think we can make this a 1.3 problem and decide how find should be defined when we meet up as its definition can be used for vaccinaiton as well.

**Comment by francisyzy** [comment]
change to `char` find, so if `find e` then will list everyone with `e` inside their name.

Then `find John John`, will show up with someone named `John John` only, `John Doe` will **not** show up.

**Comment by daitenshionyan** [comment]
I propose this:

```java
import java.util.List;
import java.util.Scanner;

public class Main {
    public static void main(String[] args) {
        try (Scanner scanner = new Scanner(System.in)) {
            while (scanner.hasNext()) {
                String text = scanner.nextLine();
                String patternString = scanner.nextLine();
                List<String> patterns = List.of(patternString.split("\\s+"));
                System.out.println(isMatching(text, patterns));
            }
        }
    }


    public static boolean isMatching(String text, List<String> patterns) {
        String regrex = compileRegex(patterns);
        return text.matches(regrex);
    }


    private static String compileRegex(List<String> patterns) {
        StringBuilder builder = new StringBuilder();

        for (String pattern : patterns) {
            // not shown but pattern all regrex syntax chars will have to be
            // changed to escape chars
            // eg "[" to "\["
            builder.append(String.format(".*(%s)", pattern));
        }

        builder.append(".*");
        return builder.toString();
    }
}
```

Testing

![image](https://user-images.githubusercontent.com/100074448/226953126-f81539ef-1c2a-4d47-8182-203e98d06cb4.png)

![image](https://user-images.githubusercontent.com/100074448/226954025-019a5096-cd50-4538-b906-5fe585d4f83a.png)


As in the comments, special characters will have to be converted to escape characters else errors may result.
Also code presented her is case sensitive. To make it insensitive convert both `text` and `patternString` to a single case.
