### ISSUE TITLE
As a careless user, I can delete patients/appointments

### ISSUE THREAD

**Issue by francisyzy** [AY2223S2-CS2103-F11-3/tp#20]
so that I can remove mistakes (Soft Delete)

**Comment by francisyzy** [comment]
Changed to hard delete because later peer evaluation people might be confused with this fancy feature.

**Comment by nusE0726844** [comment]
The DeleteCommand for Appointment Class has been implemented at #182.

**Comment by daitenshionyan** [comment]
Both deletes working!!
