### ISSUE TITLE
As a receptionist, I can get the patient's contact easily

### ISSUE THREAD

**Issue by francisyzy** [AY2223S2-CS2103-F11-3/tp#21]
so that I can contact them when needed.

**Comment by francisyzy** [comment]
@nusE0726844 Do you want to do this feature? I think can finish this user story by displaying the user's name and contact number. It will show that the receptionist can access patient's contact easily as it shows up in their current appointment list already

**Comment by daitenshionyan** [comment]
I think this can be under patient find.

Like we can add more ways to find a patient such as:
* patient find `<patientID> `
* patien find [--n `<name>`] [--p `<phone>`]     ....... rest of patient stuff     ........

This should make it easy to get patient's contacts.
