### ISSUE TITLE
Add Keyword component design to DG

### ISSUE THREAD

**Issue by francisyzy** [AY2223S2-CS2103-F11-3/tp#269]
So that the developers will know how to use that feature.

New section under Design > Architecture > Model component > Keyword component.

**Comment by nusE0726844** [comment]
A draft for the Keyword component design was made in https://github.com/AY2223S2-CS2103-F11-3/tp/pull/355

**Comment by slackernoob** [comment]
Addressed in #387 . Closing issue.
