### ISSUE TITLE
Appointment `add` UG restriction format does not link to syntax

### ISSUE THREAD

**Issue by daitenshionyan** [AY2223S2-CS2103-F11-3/tp#348]
![image](https://user-images.githubusercontent.com/100074448/229983146-63b0e8d3-9dc0-470b-8c4d-bbd444998aa6.png)

Highlight placeholders similar to appointment `edit`. (I forgot to update this)

**Comment by nusE0726844** [comment]
It seems to have been addressed in [#9dab600](https://github.com/AY2223S2-CS2103-F11-3/tp/pull/351/commits/9dab6003ed4cb472d487f62787eedfda090c9cdf) by @[daitenshionyan](https://github.com/daitenshionyan)
