### ISSUE TITLE
Wrong command format displayed when add command is incorrectly used

### ISSUE THREAD

**Issue by slackernoob** [AY2223S2-CS2103-F11-3/tp#82]
Requires fixing of add command format that is displayed to users

**Comment by francisyzy** [comment]
BUG:
![image](https://user-images.githubusercontent.com/24467184/225092416-f3919ed1-aab4-4497-b8a5-5f0d2c5923c7.png)

**Comment by francisyzy** [comment]
See #177 to see what the fixed GUI looks like
