### ISSUE TITLE
Move Address Book to Patient Records etc.

### ISSUE THREAD

**Issue by francisyzy** [AY2223S2-CS2103-F11-3/tp#94]
There are too many instance of Address Book that we need to rename to VMS or something.

It is no longer fit for name for our purpose.

If anyone else have a better idea to replace `Address Book` to something else please put in the comments below. Don’t forget to like and subscribe!

**Comment by daitenshionyan** [comment]
I suggest `PatientManager` to match `VaxTypeManager`.

`AddressBookStorage`, `JsonAddressBookStorage`, etc will have to be renamed too.

_liked and subed_

**Comment by francisyzy** [comment]
![Uploading image.png…]()
nice
